name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup toolchain
      run: rustup target add i686-pc-windows-msvc
    - name: Build release
      run: cargo build --target=i686-pc-windows-msvc --release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: bftracks-launcer-32bit
        path: |
          target\i686-pc-windows-msvc\release\*.exe
          target\i686-pc-windows-msvc\release\*.pdb
