name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup toolchain
      run: |
        rustup target add i686-pc-windows-msvc
        rustup component add clippy
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Build release
      run: cargo build --target=i686-pc-windows-msvc --release