name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup toolchain
      run: rustup target add i686-pc-windows-msvc
    - name: Build release
      run: cargo build --target=i686-pc-windows-msvc --release
